#!/bin/bash

# Function to generate/update the Makefile
generate_makefile() {
	# Get the name of the executable
	program_name=$(ls *.c | head -n 1 | cut -d '.' -f 1)
    SRC=$(ls *.c 2>/dev/null)
    if [ -z "$SRC" ]; then
        echo "No C source files found in the current directory."
        return
    fi
    cat <<EOT > Makefile
CC = gcc
CFLAGS = -Wall -Wextra -Werror
NAME = $program_name
SRC = $(ls *.c | tr '\n' ' ')
OBJ = \$(SRC:.c=.o)
all: \$(NAME)
\$(NAME): \$(OBJ)
	\$(CC) \$(CFLAGS) -o \$(NAME) \$(OBJ)
.c.o:
	\$(CC) \$(CFLAGS) -c \$<
clean:
	rm -f \$(OBJ) \$(NAME)
EOT
    echo "Makefile created successfully."
}
while true; do
    generate_makefile
    sleep 5  # Adjust the sleep time as needed
done
